name: paulthomson
favicon: null
layout_spectrum: 0.3533710688352585
typography_spectrum: 0.43789794691838324
title: Paul Thomson composer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7e7e7'
    - '#040702'
    - '#fa7115'
    - '#09aec4'
    - '#ebe000'
  brandStrength: 0.625
  lightness: 0.7372492754366249
  saturation: 0.36092145601287484
  rhythmicContrast: 0.8608654739800841
purpose: []
