name: paulthomson
favicon: null
layout_spectrum: 0.3533710688352585
typography_spectrum: 0.43789794691838324
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9080907383468002
  lightness: 0.7372492754366249
  saturation: 0.36092145601287484
  rhythmicContrast: 0.8608654739800841
purpose: []
